spring:
  application:
    name: Competence
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org:
      springframework:
        security: DEBUG
cors:
  allowedOrigins:
    - http://localhost:4200
    - https://localhost:4200
  allowedMethods:
    - PUT
    - DELETE
    - POST
    - GET
  allowedHeaders:
    - Authorization
    - Content-Type