INSERT INTO skill (name)
VALUES ('MANAGING_PROJECTS'),
       ('INTERPERSONAL'),
       ('ANGULAR'),
       ('JAVA'),
       ('SPRING_BOOT'),
       ('SPRING'),
       ('KAFKA'),
       ('TERRAFORM'),
       ('REACT'),
       ('NODE_JS'),
       ('CHATGPT'),
       ('TWITTER'),
       ('EXPRESS'),
       ('PYTHON'),
       ('DOCKER'),
       ('GRAPHQL'),
       ('VUE_JS'),
       ('RUBY_ON_RAILS'),
       ('SVELTE'),
       ('PHP'),
       ('LARAVEL'),
       ('MYSQL'),
       ('BASH'),
       ('ELASTICSEARCH'),
       ('AZURE'),
       ('DJANGO'),
       ('REDIS'),
       ('JIRA'),
       ('FIREBASE'),
       ('REACT_NATIVE'),
       ('MONGODB'),
       ('KOTLIN'),
       ('PROMETHEUS'),
       ('CIRCLECI'),
       ('NEXT_JS'),
       ('GO'),
       ('GIN'),
       ('CASSANDRA'),
       ('SWIFT'),
       ('LOGSTASH'),
       ('HEROKU'),
       ('NUXT_JS'),
       ('C_SHARP'),
       ('ASP_NET'),
       ('SQLITE'),
       ('RUST'),
       ('FLUENTD'),
       ('DIGITALOCEAN'),
       ('EMBER_JS'),
       ('SCALA'),
       ('PLAY_FRAMEWORK'),
       ('DYNAMODB'),
       ('OBJECTIVE_C'),
       ('GRAFANA'),
       ('NETLIFY'),
       ('BACKBONE_JS'),
       ('PERL'),
       ('CATALYST'),
       ('COUCHDB'),
       ('HASKELL'),
       ('SPLUNK'),
       ('VERCEL'),
       ('SUPABASE')
ON CONFLICT (name) DO NOTHING;

INSERT INTO project (title, description)
VALUES ('Jungle', 'Tropical fruits delivery system'),
       ('EVO', 'Software for accountants'),
       ('CloudSync', 'File synchronization service for cloud storage'),
       ('HealthHub', 'Telemedicine platform for remote healthcare'),
       ('EduTrack', 'Student performance tracking system for schools'),
       ('StockAnalyzer', 'Real-time stock market analysis tool'),
       ('FitLife', 'Fitness app with personalized workout plans'),
       ('ShopMate', 'E-commerce platform for small businesses'),
       ('TravelBuddy', 'Travel planning and booking application'),
       ('GreenThumb', 'Urban gardening community platform'),
       ('EventHive', 'Event management and ticketing system'),
       ('CodeCollab', 'Collaborative coding environment for developers'),
       ('PetCare', 'Pet health and wellness management app'),
       ('HomeCook', 'Recipe sharing and meal planning app'),
       ('SafeDrive', 'Vehicle telematics and safety monitoring system'),
       ('BookClub', 'Online community for book enthusiasts'),
       ('MindSpace', 'Meditation and mental health app'),
       ('FarmFresh', 'Farm-to-table marketplace'),
       ('DevDash', 'Developer productivity and analytics dashboard'),
       ('ArtShare', 'Platform for artists to share and sell their work')
ON CONFLICT (title) DO NOTHING;
